### PR TITLE
I added python3.9.

### LINKED ISSUE #61: [FEATURE] Run Python 3.9 builds
- Add `39` to `envlist` in `tox.ini`
- Add `39` to `depends` of the `coverage-report` job in `tox.ini`
- Add `Programming Language :: Python :: 3.9` to the classifiers list in `setup.py`
- Add Python 3.9 job in `.github/workflows/build.yml` similarly to other builds

### PR DESCRIPTION
**Pull request by pengincoalition**
Close #61
Add python3.9.

🚨Please review the
[guidelines for contributing](https://github.com/kiwicom/pytest-recording/blob/master/CONTRIBUTING.rst)
to this repository.

### Description

I added python3.9.

### CODE REVIEW

**Comment by Stranger6667** [comment]
Cool! I suggest taking a look at this commit - https://github.com/schemathesis/schemathesis/commit/1691780f96ff7a4784a939dbba1f7f29843b08c7

The version string on GitHub actions requires some extra changes

**Comment by pengincoalition** [comment]
Excuse me.
I'm sorry if I missed important things.
Could you tell how to solve the error message that "Please provide an upload token from codecov.io with valid arguments"?

**Comment by Stranger6667** [comment]
> Could you tell how to solve the error message that "Please provide an upload token from codecov.io with valid arguments"?

Unfortunately, this part can't be easily solved for forked repositories. I suggest to skip this message - I'll merge the PR if other things are resolved :)

**Comment by Stranger6667** [comment]
However, the only thing left is the commit message, but I'll fix it on merge :) Thank you for your contribution

**Comment by pengincoalition** [comment]
Thank you, too.
I that is the beginner could learned a lot about OSS by this PR!

**Comment by Stranger6667** [comment]
Cool! Let me know if I can provide some more info about this PR or the project itself :)

**Pull request merged**
